# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

InviteCode.create([
	{ code: 'blackalder', used: false },
	{ code: 'mapleash', used: false },
	{ code: 'bearberry', used: false },
	{ code: 'beech', used: false },
	{ code: 'bamboo', used: false },
	{ code: 'boxelder', used: false },
	{ code: 'butterflyweed', used: false },
	{ code: 'californiasycamore', used: false },
	{ code: 'chrysanthemum', used: false },
	{ code: 'coakum', used: false },
	{ code: 'colicweed', used: false },
	{ code: 'crowfoot', used: false },
	{ code: 'cucumber', used: false },
	{ code: 'poorlanddaisy', used: false },
	{ code: 'devilsbite', used: false },
	{ code: 'dewberry', used: false },
	{ code: 'silkydogwood', used: false },
	{ code: 'eucalyptus', used: false },
	{ code: 'fellenwort', used: false },
	{ code: 'feverbush', used: false },
	{ code: 'flax', used: false },
	{ code: 'fumewort', used: false },
	{ code: 'gilliflower', used: false },
	{ code: 'goosetongue', used: false },
	{ code: 'groundberry', used: false },
	{ code: 'harlequin', used: false },
	{ code: 'hayfeverweed', used: false },
	{ code: 'hellebore', used: false },
	{ code: 'winterberryholly', used: false },
	{ code: 'summerlilac', used: false },
	{ code: 'meadowholly', used: false },
	{ code: 'swampholly', used: false },
	{ code: 'inkberryholly', used: false },
	{ code: 'europeanholly', used: false },
	{ code: 'deciduousholly', used: false },
	{ code: 'huckleberry', used: false },
	{ code: 'houseleek', used: false },
	{ code: 'indianhemp', used: false },
	{ code: 'indianposy', used: false },
	{ code: 'ivy', used: false },
	{ code: 'itchweed', used: false },
	{ code: 'juneberry', used: false },
	{ code: 'juniper', used: false },
	{ code: 'keek', used: false },
	{ code: 'kinnikinnik', used: false },
	{ code: 'kousa', used: false },
	{ code: 'kudzu', used: false },
	{ code: 'laceflower', used: false },
	{ code: 'lambsfoot', used: false },
	{ code: 'lavender', used: false },
	{ code: 'leek', used: false },
	{ code: 'maize', used: false },
	{ code: 'ashleavedmaple', used: false },
	{ code: 'blackmaple', used: false },
	{ code: 'creekmaple', used: false },
	{ code: 'cutleafmaple', used: false },
	{ code: 'mapleash', used: false },
	{ code: 'moosemaple', used: false },
	{ code: 'redrivermaple', used: false },
	{ code: 'silverleafmaple', used: false },
	{ code: 'softmaple', used: false },
	{ code: 'stripedmaple', used: false },
	{ code: 'sugarmaple', used: false },
	{ code: 'swampmaple', used: false },
	{ code: 'watermaple', used: false },
	{ code: 'whitemaple', used: false },
	{ code: 'honeymesquite', used: false },
	{ code: 'softmaple', used: false },
	{ code: 'milfoil', used: false },
	{ code: 'bluntleavedmilkweed', used: false },
	{ code: 'commonmilkweed', used: false },
	{ code: 'orangemilkweed', used: false },
	{ code: 'swampmilkweed', used: false },
	{ code: 'rosemilkweed', used: false },
	{ code: 'whorledmilkweed', used: false },
	{ code: 'yellowmilkweed', used: false },
	{ code: 'milkytassel', used: false },
	{ code: 'corkoak', used: false },
	{ code: 'coastliveoak', used: false },
	{ code: 'championoak', used: false },
	{ code: 'californiablackoak', used: false },
	{ code: 'buroak', used: false },
	{ code: 'algerianoak', used: false },
	{ code: 'pinoak', used: false },
	{ code: 'sessileoak', used: false },
	{ code: 'scruboak', used: false },
	{ code: 'scarletoak', used: false },
	{ code: 'redoak', used: false },
	{ code: 'pedunculateoak', used: false },
	{ code: 'mossycupwhiteoak', used: false },
	{ code: 'mirbecksoak', used: false },
	{ code: 'islandoak', used: false },
	{ code: 'englishoak', used: false },
	{ code: 'easternblackoak', used: false },
	{ code: 'spanishoak', used: false },
	{ code: 'spottedoak', used: false },
	{ code: 'swampoak', used: false },
	{ code: 'valleyoak', used: false },
	{ code: 'whiteoak', used: false },
	{ code: 'yellowbarkoak', used: false },
	{ code: 'olive', used: false },
	{ code: 'commononion', used: false },
	{ code: 'treeonion', used: false },
	{ code: 'wildonion', used: false },
	{ code: 'noddingonion', used: false },
	{ code: 'redosier', used: false },
])

#Category.create([
#	{ category: 'Plants', parentCategory: ''},
#	{ category: 'Annuals', parentCategory: 'Plants'},
#	{ category: 'Perennials', parentCategory: 'Plants'},
#	{ category: 'Aquatic', parentCategory: 'Plants'},
#	{ category: 'Groundcovers', parentCategory: 'Plants'},
#	{ category: 'Ferns', parentCategory: 'Plants'},
#	{ category: 'Herbs', parentCategory: 'Plants'},
#	{ category: 'Interior', parentCategory: 'Plants'},
#	{ category: 'Tropicals', parentCategory: 'Plants'},
#	{ category: 'Grasses', parentCategory: 'Plants'},
#	{ category: 'Roses', parentCategory: 'Plants'},
#	{ category: 'Shrubs - Deciduous', parentCategory: 'Plants'},
#	{ category: 'Shrubs - Evergreen', parentCategory: 'Plants'},
#	{ category: 'Trees - Deciduous', parentCategory: 'Plants'},
#	{ category: 'Trees - Evergreen', parentCategory: 'Plants'},
#	{ category: 'Materials', parentCategory: ''},
#	{ category: 'Building Supplies', parentCategory: 'Materials'},
#	{ category: 'Chemicals', parentCategory: 'Materials'},
#	{ category: 'Drainage Supplies', parentCategory: 'Materials'},
#	{ category: 'Electrical Supplies', parentCategory: 'Materials'},
#	{ category: 'Garden Accessories', parentCategory: 'Materials'},
#	{ category: 'Irrigation Supplies', parentCategory: 'Materials'},
#	{ category: 'Lighting', parentCategory: 'Materials'},
#	{ category: 'Seed', parentCategory: 'Materials'},
#	{ category: 'Soils', parentCategory: 'Materials'},
#	{ category: 'Stone', parentCategory: 'Materials'},
#	{ category: 'Misc. Supplies', parentCategory: 'Materials'},
#	{ category: 'Equipment', parentCategory: ''}
#])
